dist: trusty
language: node_js
node_js:
- 8

addons:
  apt:
    packages:
      - pulseaudio

env:
  global:
    - DISPLAY=:99.0

  matrix:
    - BROWSER=chrome BVER=stable
    - BROWSER=firefox BVER=stable

matrix:
  fast_finish: true

before_script:
  - sh -e /etc/init.d/xvfb start
  - pulseaudio --start

script:
  - npm test
